export const tecnologies = [
  { skill: "React", level: "Avançado", category: "Frontend" },
  { skill: "TypeScript", level: "Avançado", category: "Frontend" },
  { skill: "RStudio", level: "Básico", category: "Data" },
  { skill: "JavaScript", level: "Intermediário", category: "Frontend" },
  { skill: "MySQL", level: "Intermediário", category: "Backend" },
  { skill: "Tableau", level: "Básico", category: "Data" },
  { skill: "Python", level: "Intermediário", category: "Backend" },
  { skill: "React Native", level: "Intermediário", category: "Mobile" },
  { skill: "MongoDB", level: "Básico", category: "Backend" },
  { skill: "Java", level: "Intermediário", category: "Backend" },
  { skill: "Git/GitHub", level: "Avançado", category: "DevOps" },
  { skill: "AWS", level: "Básico", category: "Cloud" },
  { skill: "VBA", level: "Intermediário", category: "Data" },
  { skill: "UML Modeling", level: "Avançado", category: "Architecture" },
  { skill: "C", level: "Básico", category: "Backend" },
  { skill: "Azure", level: "Intermediário", category: "Cloud" },
  { skill: "Astah", level: "Intermediário", category: "Architecture" },
  { skill: "Estatística", level: "Intermediário", category: "Data" },
  { skill: "Figma", level: "Intermediário", category: "Design" },
  { skill: "R", level: "Intermediário", category: "Data" },
  { skill: "Algoritmos", level: "Intermediário", category: "Backend" },
  { skill: "Excel", level: "Intermediário", category: "Data" },
  { skill: "Power BI", level: "Básico", category: "Data" },
  { skill: "Flutter", level: "Avançado", category: "Mobile" },
  {
    skill: "Microsoft Office",
    level: "Intermediário",
    category: "Productivity",
  },
  { skill: "Jupyter", level: "Intermediário", category: "Data" },
  { skill: "Dart", level: "Avançado", category: "Mobile" },
];
